using AlbumApp1._0._1.Views;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Microsoft.UI.Dispatching;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Diagnostics.Eventing.Reader;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace AlbumApp1._0._1.ViewModels.SplashScreen
{
    public partial class SplashScreenViewModel : ObservableObject
    {

        private readonly DispatcherQueue dispatcherQueue = DispatcherQueue.GetForCurrentThread();

        [ObservableProperty]
        public partial string? Text { get; set; }
        [ObservableProperty]
        public partial int Value { get; set; }
        public SplashScreenViewModel()
        {
            //var progress = new Progress<int>();
            //progress.ProgressChanged += (sender, e) =>
            //{

            //    OnLoading().Wait();

            //};
            //OnPropertyChanged(nameof(Value));


     

            // Initial values — these will raise PropertyChanged (generated by CommunityToolkit)
   
            StartLoadingAsync();
        }
        //private Task RunOnUIAsync(Action action)
        //{
        //    if (dispatcherQueue == null)
        //    {
        //        No dispatcher(e.g.unit tests) — run directly.
        //        action();
        //        return Task.CompletedTask;
        //    }

        //    if (dispatcherQueue.HasThreadAccess)
        //    {
        //        action();
        //        return Task.CompletedTask;
        //    }

        //    var tcs = new TaskCompletionSource<object?>();
        //    TryEnqueue runs on UI thread; signal when done.
        //   dispatcherQueue.TryEnqueue(() =>
        //   {
        //       try
        //       {
        //           action();
        //           tcs.SetResult(null);
        //       }
        //       catch (Exception ex)
        //       {
        //           tcs.SetException(ex);
        //       }
        //   });

        //    return tcs.Task;
        //}
        bool IsUIThread()
        {
            return null != dispatcherQueue;
        }

        public async void StartLoadingAsync()
        {
            if(IsUIThread()==true){
                for (int i = 0; i <= 100; i += 5)
                {
                    await Task.Delay(500);

                    // Ensure property updates happen on UI thread.
                    //await RunOnUIAsync(() =>
                    //{
                    //    Text = $"Loading {i}%...";
                    //    Value = i;
                    //});
                    bool isQueued = this.dispatcherQueue.TryEnqueue(Microsoft.UI.Dispatching.DispatcherQueuePriority.Normal, () =>
                    {
                        Text = $"Loading {i}%...";
                        Value = i;
                    });
                }

                //await RunOnUIAsync(() => Text = "Done!");
            }
            else
            {
                return;
            }
        }
       
        //TODO: Do some actual work







    }
    }

