<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>AlbumApp1._0._1</RootNamespace>
    <ApplicationIcon>Assets/WindowIcon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64;x86;arm64</Platforms>
    <RuntimeIdentifiers>win-x64;win-x86;win-arm64</RuntimeIdentifiers>
    <PublishProfile>Properties\PublishProfiles\win-$(Platform).pubxml</PublishProfile>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Views\Basic\AboutProjectView.xaml" />
    <None Remove="Views\Basic\AlbumsView.xaml" />
    <None Remove="Views\Basic\ArchiveView.xaml" />
    <None Remove="Views\Basic\BasicWindow.xaml" />
    <None Remove="Views\Basic\FavouritesView.xaml" />
    <None Remove="Views\Basic\FeedbackView.xaml" />
    <None Remove="Views\Basic\PhotosView.xaml" />
    <None Remove="Views\Basic\QuestionsView.xaml" />
    <None Remove="Views\Basic\ShellView.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.9" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.250916003" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.WinUI.Managed" Version="2.0.9" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.9" />

  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlbumApp1.0.1.Core\AlbumApp1.0.1.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Page Update="Styles\ErrorTemplates.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\Basic\AboutProjectView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\Basic\QuestionsView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\Basic\ArchiveView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\Basic\FeedbackView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\Basic\FavouritesView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\Basic\ShellView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\Basic\AlbumsView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\Basic\PhotosView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\Basic\BasicWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Styles\TemplatesViewModelsToViews.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Windows\" />
    <Folder Include="Repositories\" />
    <Folder Include="Styles\DayOrNight\" />
  </ItemGroup>
  
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
</Project>
